// /d/shenlong/unique_weapons.h
// Last Modified by winder on Jul. 12 2002

mapping unique_weapons  = ([
	"白龙剑"   : "/clone/weapon/treasure/baihong-jian.lpc",
	"匕首"     : "/clone/weapon/treasure/bishou.lpc",
	"屠龙刀"   : "/clone/weapon/treasure/dragonblade.lpc",
	"伏魔刀"   : "/clone/weapon/treasure/fumo-dao.lpc",
	"干将剑"   : "/clone/weapon/treasure/ganjiang-jian.lpc",
	"碧水剑"   : "/clone/weapon/treasure/greenwater-sword.lpc",
	"五毒剪"   : "/clone/weapon/treasure/jiandao.lpc",
	"金凤钩"   : "/clone/weapon/treasure/jinfenggou.lpc",
	"夺命金花" : "/clone/weapon/treasure/jinhua.lpc",
	"金轮"     : "/clone/weapon/treasure/jinlun.lpc",
	"金蛇剑"   : "/clone/weapon/treasure/jinshe-jian.lpc",
	"金乌杖"   : "/clone/weapon/treasure/jinwu-staff.lpc",
	"闯王宝刀" : "/clone/weapon/treasure/king-blade.lpc",
	"狼牙棒"   : "/clone/weapon/treasure/langyabang.lpc",
	"灵蛇杖"   : "/clone/weapon/treasure/lingshezhang.lpc",
	"沥泉枪"   : "/clone/weapon/treasure/liquan-qiang.lpc",
	"龙泉剑"   : "/clone/weapon/treasure/longquan-jian.lpc",
	"莫邪剑"   : "/clone/weapon/treasure/moye-jian.lpc",
	"白玉瑶琴" : "/clone/weapon/treasure/qin.lpc",
	"青光剑"   : "/clone/weapon/treasure/qingguang-jian.lpc",
	"南海神木" : "/clone/weapon/treasure/sea-wood.lpc",
	"倚天剑"   : "/clone/weapon/treasure/skysword.lpc",
	"血刀"     : "/clone/weapon/treasure/xblade.lpc",
	"玄铁剑"   : "/clone/weapon/treasure/xuantie-sword.lpc",
	"玄铁重剑" : "/clone/weapon/treasure/xuantie-jian.lpc",
	"银轮"     : "/clone/weapon/treasure/yinlun.lpc",
	"游龙剑"   : "/clone/weapon/treasure/youlong-jian.lpc",
	"鱼肠剑"   : "/clone/weapon/treasure/yuchang-jian.lpc",
	"越王剑"   : "/clone/weapon/treasure/yuewang-jian.lpc",
	"湛卢剑"   : "/clone/weapon/treasure/zhanlu-jian.lpc",
	"真武剑"   : "/clone/weapon/treasure/zhenwu-jian.lpc",
	"金蛇锥"   : "/d/jinshe/obj/jinshe-zhui.lpc",
	"绿玉棒"   : "/kungfu/class/gaibang/obj/lvyv_bang.lpc",
]);
